### PR TITLE
Adding Apple silicon support for ENET Native library build

### PR DESCRIPTION
**Pull request by geopaulm**
Made changes to CMakeLists.txt so that dylib includes both x86_64 & arm64

### CODE REVIEW

**Comment by nxrighthere** [comment]
Won't it break compilation on a non-ARM machine?

**Comment by geopaulm** [comment]
> Won't it break compilation on a non-ARM machine?
@nxrighthere It won't. You can cross compile and build for multiple architectures. (Intel based machines can build for arm64)

**Comment by nxrighthere** [comment]
Thanks!

**Comment by tovgroliv** [comment]
The server is initialized but not accessible to the client. Not accessible in localhost (127.0.0.1) and external connection (192.169.100.2). Everything works on Windows and Linux.

Do you know why it doesn't work? Have you encountered this problem?
I will be glad for any help! Thank you!

**Comment by tovgroliv** [comment]
> The server is initialized but not accessible to the client. Not accessible in localhost (127.0.0.1) and external connection (192.169.100.2). Everything works on Windows and Linux.
> 
> Do you know why it doesn't work? Have you encountered this problem? I will be glad for any help! Thank you!

I was able to track down the error. Previously, I specified a specific IP address to start the server. This works on all systems except MacOS.

**Pull request merged**
